name: publish
on: [push]
jobs:
  nextcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the nextcloud Docker image
        run: |
         docker build . --tag ghcr.io/biotob81/nextcloud:latest
         docker run ghcr.io/biotob81/nextcloud:latest
         docker push ghcr.io/biotob81/nextcloud:latest
